## catalog of libraries and plugins used to build the FuzeCreek project

[versions]

checkstyle = "12.3.1"
jme = "3.9.0-beta1"

[libraries]

acorus = "com.github.stephengold:Acorus:2.0.2"
heart = "com.github.stephengold:Heart:9.2.0"
jme3-jogg = { module = "org.jmonkeyengine:jme3-jogg", version.ref = "jme" }
jme3-lwjgl3 = { module = "org.jmonkeyengine:jme3-lwjgl3", version.ref = "jme" }
jme3-plugins = { module = "org.jmonkeyengine:jme3-plugins", version.ref = "jme" }
skyControl = "com.github.stephengold:SkyControl:1.1.0"

[bundles]

[plugins]
